//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsToolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsToolkit.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] background_operators {
            get {
                object obj = ResourceManager.GetObject("background_operators", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_amiya_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_amiya_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_angelina_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_angelina_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_bluepoison_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_bluepoison_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_ceylon_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_ceylon_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_doctor_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_doctor_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_exusiai_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_exusiai_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_gravel_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_gravel_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] operator_platinum_e0 {
            get {
                object obj = ResourceManager.GetObject("operator_platinum_e0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--Sample Data--&gt;
        ///&lt;OperatorsList xmlns=&quot;http://schema.livestudio.com/Operators.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Operator Name=&quot;博士&quot; Sex=&quot;Male&quot; Star=&quot;6&quot; ImageCodename=&quot;doctor_e0&quot; OperatorClass=&quot;Specialist&quot; HasSkin=&quot;false&quot;&gt;
        ///    &lt;Birthday&gt;
        ///      &lt;Month&gt;5&lt;/Month&gt;
        ///      &lt;Day&gt;14&lt;/Day&gt;
        ///    &lt;/Birthday&gt;
        ///  &lt;/Operator&gt;
        ///  &lt;Operator Name=&quot;阿米娅&quot; Sex=&quot;Female&quot; Star=&quot;5&quot; ImageCodename=&quot;amiya_e0&quot; OperatorC [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Operators&quot;
        ///    targetNamespace=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    xmlns:mstns=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;OperatorsList&quot; type=&quot;OperatorsList&quot;/&gt;
        ///
        ///  &lt;xs:complexType name=&quot;OperatorsList&quot;&gt;
        ///    &lt;xs:sequence maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Op [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string OperatorsXSD {
            get {
                return ResourceManager.GetString("OperatorsXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_0 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_1 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_2 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_3 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_4 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_5 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_6 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_7 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] storyimage_main_8 {
            get {
                object obj = ResourceManager.GetObject("storyimage_main_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_amiya_bg {
            get {
                object obj = ResourceManager.GetObject("ui_amiya_bg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_caster {
            get {
                object obj = ResourceManager.GetObject("ui_caster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_defender {
            get {
                object obj = ResourceManager.GetObject("ui_defender", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_guard {
            get {
                object obj = ResourceManager.GetObject("ui_guard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_medic {
            get {
                object obj = ResourceManager.GetObject("ui_medic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_missing {
            get {
                object obj = ResourceManager.GetObject("ui_missing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_records {
            get {
                object obj = ResourceManager.GetObject("ui_records", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_sniper {
            get {
                object obj = ResourceManager.GetObject("ui_sniper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_specialist {
            get {
                object obj = ResourceManager.GetObject("ui_specialist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_story_background1 {
            get {
                object obj = ResourceManager.GetObject("ui_story_background1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_story_background2 {
            get {
                object obj = ResourceManager.GetObject("ui_story_background2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_story_background3 {
            get {
                object obj = ResourceManager.GetObject("ui_story_background3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_supporter {
            get {
                object obj = ResourceManager.GetObject("ui_supporter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_tape {
            get {
                object obj = ResourceManager.GetObject("ui_tape", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ui_vanguard {
            get {
                object obj = ResourceManager.GetObject("ui_vanguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
